when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false

    framework:
        profiler:
            enabled: true
            collect: true
            collect_serializer_data: true
        
