controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# api/config/routes.yaml
login:
    path: /api/login
    methods: ["POST"]

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    methods: ["POST"]
