controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# api/config/routes.yaml
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    methods: ["POST"]

customer_gesdinet_jwt_refresh_token:
    path: /api/customers/token/refresh
    methods: ["POST"]

customer_login_check:
    path: /api/customers/login
    methods: ["GET"]

user_login:
    path: /api/login
    methods: ["POST"]